//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ObjToAn8.rc
//
#define IDD_OBJTOAN8_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDC_BUTTON1                     1000
#define IDC_BUTTON2                     1001
#define IDC_EDIT1                       1002
#define IDC_EDIT2                       1003
#define IDC_BUTTON3                     1004
#define IDC_CHECKSPECIALKEYWORD         1005
#define IDC_CHECKMERGELIKEMATERIALS     1006
#define IDC_CHECKMERGELIKEMATERIALS2    1007
#define IDC_CHECKMERGELIKEMATERIALS3    1008
#define IDC_CHECKMERGELIKEMATERIALS4    1009
#define IDC_CHECKMERGELIKEMATERIALS5    1010
#define IDC_CHECKIGNORESHADING          1011
#define IDC_CHECKROUNDVERTICESTENTHS    1012
#define IDC_CHECKRECENTEROBJECTS        1013
#define IDC_CHECKSCALEVERTICES          1014
#define IDC_EDITSCALEVERTICES           1015
#define IDC_BUTTONCHOOSEREPLACES        1016
#define IDC_CHECKNOGROUPS               1017
#define IDC_EDITMATERIALREPLACES        1018
#define IDC_CHECKREPLACE                1019
#define IDC_CHECKFIXNIKAKS              1020
#define IDC_CHECKSCALEDIFFUSESHADING    1021
#define IDC_EDITSCALEDIFFUSESHADING     1022
#define IDC_CHECKSCALEDIFFUSESHADING2   1023
#define IDC_CHECKMOVEPOINTS             1024
#define IDC_CHECKIGNORESHADING2         1025
#define IDC_EDITX                       1026
#define IDC_EDITX2                      1027
#define IDC_EDITX3                      1028
#define IDC_CHECKAMBIENTSHADING         1029
#define IDC_EDITAMBIENTSHADING          1030
#define IDC_CHECKSCALESPECULARSHADING   1031
#define IDC_EDITSPECULARSHADING         1032
#define IDC_CHECKSCALEAMBIENTFACTOR     1033
#define IDC_CHECKSCALEDIFFUSEFACTOR     1034
#define IDC_EDITSCALEAMBIENTFACTOR      1035
#define IDC_EDITSCALEDIFFUSEFACTOR      1036
#define IDC_CHECKDISABLEAUTOSHADING     1037
#define IDC_CHECKDISABLEAUTOSHADING2    1038
#define IDC_CHECKDEFAULTSHADING         1038
#define IDC_CHECKNOGROUPS2              1039
#define IDC_CHECKAUTOCALCUVS            1040
#define IDC_CHECKSCALEUVS               1041
#define IDC_EDITSCALEVERTICES2          1042
#define IDC_CHECKSPECIFYTILESIZE        1043
#define IDC_EDITSCALEVERTICES3          1044
#define IDC_EDITSCALEVERTICES4          1045
#define IDC_EDITGROUPFILTER             1046
#define IDC_CHECKREGEXGROUPFILTER       1047
#define IDC_CHECKROUNDVERTICESHUNDREDTHS 1048
#define IDC_GROUPFBXEXPORTER            1049
#define IDC_COMBOFBXEXPORTER            1050
#define IDC_LABELFBXEXPORTTYPE          1051
#define IDC_BUTTONCHOOSEOVERRIDESKELETON 1052
#define IDC_CHECKOVERRIDESKELETON       1053
#define IDC_EDITOVERRIDESKELETON        1054
#define IDC_CHECKFIXSPACESINFBXIMAGEPATHS 1055
#define IDC_CHECKRECENTERUVS            1056
#define IDC_COMBO1                      1056
#define IDC_COMBOJOINTSRT               1056
#define IDC_JOINTMODELABEL              1057
#define IDC_LABELFBXEXPORTTYPE2         1058
#define IDC_EDIT3                       1059

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1060
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
