//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by N64SoundListTool.rc
//
#define IDOK                            1
#define IDCANCEL                        2
#define IDD_N64SOUNDLISTTOOL_DIALOG     102
#define IDR_MAINFRAME                   128
#define IDR_MENUMAIN                    129
#define IDD_DIALOGSPECIFYLOCATION       130
#define IDS_STRINGERRORREADINGCONFIG    131
#define IDS_STRINGERROR                 132
#define IDS_STRINGERRORREADINGROM       133
#define IDS_STRINGERROROPENING          134
#define IDS_STRINGERRORPROCESSING       135
#define IDS_STRINGERRORTOOSMALLFILE     136
#define IDS_STRINGERROREXTRACTINGSOUND  137
#define IDS_STRINGERROROPENINGROMOUTPUT 138
#define IDD_KONAMIADSR                  139
#define IDC_EXPORTCTLTBL                1000
#define IDC_INJECTPLACE                 1001
#define IDC_IMPORTCTLTBL                1002
#define IDC_BUTTONPLAYSND               1003
#define IDC_BUTTONTEST                  1004
#define IDC_BUTTONPLAYSND2              1005
#define IDC_BUTTONSTOPSOUND             1005
#define IDC_EDITCTL                     1005
#define IDC_EDITCTL2                    1006
#define IDC_STATICNAME                  1006
#define IDC_EDITTBL                     1006
#define IDC_EDITBANKNAME                1007
#define IDC_STATICIMPORTGROUPBOX        1008
#define IDC_STATICADDTOENDGROUPBOX      1009
#define IDC_STATICEXPORTGROUPBOX        1010
#define IDC_STATICMISCGROUPBOX          1011
#define IDC_STATICTREMGROUPBOX          1012
#define IDC_STATICVIBRGROUPBOX          1013
#define IDC_STATICSAMPLEPANSTATIC       1014
#define IDC_STATICSAMPLEVOLTEXT         1015
#define IDC_STATICVELMINTEXT            1016
#define IDC_STATICVELMAXTEXT            1017
#define IDC_STATICKEYMINTEXT            1018
#define IDC_STATICKEYMAXTEXT            1019
#define IDC_STATICKEYBASETEXT           1020
#define IDC_STATICDETUNETEXT            1021
#define IDC_STATICATTACKTIMETEXT        1022
#define IDC_STATICDECAYTIMETEXT         1023
#define IDC_STATICRELEASETIMETEXT       1024
#define IDC_STATICATTACKVOLUMETEXT      1025
#define IDC_STATICDECAYVOLUMETEXT       1026
#define IDC_STATICINSTRVOL              1027
#define IDC_STATICINSTRPAN              1028
#define IDC_STATICINSTRPRIORITY         1029
#define IDC_STATICINSTRTREM             1030
#define IDC_STATICINSTRRATE             1031
#define IDC_STATICINSTRDEPTH            1032
#define IDC_STATICINSTRDELAY            1033
#define IDC_STATICINSTRVIBTYPE          1034
#define IDC_STATICINSTRVIBRATE          1035
#define IDC_STATICINSTRVIBDEPTH         1036
#define IDC_STATICINSTRVIBDELAY         1037
#define IDC_STATICTBLINDEX              1038
#define IDC_CHECKSHORTWAVFILENAME       1039
#define IDC_BUTTONIMPORTLOOPPREDICTORS  1040
#define IDC_BUTTONEXPORTLOOPPREDICTORS  1041
#define IDC_BUTTONADDPREV               1042
#define IDC_BUTTONREMOVEPREV            1043
#define IDC_BUTTONADDPREV2              1044
#define IDC_BUTTONREMOVEPREV2           1045
#define IDC_CHECK1                      1046
#define IDC_BUTTONPLAYSND3              1046
#define IDC_CHECKHALFSAMPLINGRATE       1047
#define IDC_EDITBENDRANGE               1050
#define IDC_STATICBENDRANGE             1051
#define IDC_PERCUSSIONLABEL             1054
#define IDC_CHECKHALF_VADPCM            1055
#define IDC_SFXLABEL                    1056
#define IDC_CHECKOVERRIDERATE           1057
#define IDC_BUTTON1                     1058
#define IDC_LISTKEYBASE                 1059
#define IDC_BUTTONADDINSTRUMENT         1060
#define IDC_BUTTONDELETEINSTRUMENT      1061
#define IDC_COMBOINSTRUMENT             1062
#define IDC_CHECKUNKNOWNEADFLAG         1062
#define IDC_COMBODRUM                   1063
#define IDC_BUTTONADDPERCUSSIONBANK     1063
#define IDC_INSTRUMENTLABEL             1064
#define IDC_BUTTONDELETEPERCUSSIONBANK  1064
#define IDC_DRUMLABEL                   1065
#define IDC_BUTTONADDSFXBANK            1065
#define IDC_LABELATTACKINSTRUMENT       1066
#define IDC_BUTTONDELETESFXBANK         1066
#define IDC_LABELCOARSETUNEINSTRUMENT   1067
#define IDC_CHECKOVERRIDET1             1067
#define IDC_LABELFINETUNEINSTRUMENT     1068
#define IDC_LABELDECAYTIMEINSTRUMENT    1069
#define IDC_LABELRELEASETIMEINSTRUMENT  1070
#define IDC_LABELUNKNOWNINSTRUMENT1     1071
#define IDC_LABELUNKNOWNINSTRUMENT2     1072
#define IDC_EDITCOARSETUNEINSTRUMENT    1074
#define IDC_EDITFINETUNEINSTRUMENT2     1075
#define IDC_BUTTONKONAMIADSRBUTTON      1075
#define IDC_EDITATTACKTIMEINSTRUMENT    1076
#define IDC_T1GROUPLABEL                1076
#define IDC_EDITDECAYTIMEINSTRUMENT     1077
#define IDC_T1INDEXLABEL                1077
#define IDC_EDITRELEASETIMEINSTRUMENT   1078
#define IDC_COMBOT1INDEXCOMBO           1078
#define IDC_EDITUNKNOWN1INSTRUMENT      1079
#define IDC_T1SUBBANK                   1079
#define IDC_EDITUNKNOWN2INSTRUMENT      1080
#define IDC_COMBOT1SUBBANK              1080
#define IDC_T1INSTRUMENTLABEL           1081
#define IDC_COMBOT1SUBBANK2             1082
#define IDC_T1SOUNDLABEL                1083
#define IDC_COMBOT1SOUND                1084
#define IDC_EDITT1FREQUENCY             1085
#define IDC_T1FREQUENCYLABEL            1086
#define IDC_T1FLAGSLABEL                1087
#define IDC_EDITT1FLAGS                 1088
#define IDC_LABELATTACKDRUM             1094
#define IDC_LABELCOARSEDRUM             1095
#define IDC_LABELFINETUNEDRUM           1096
#define IDC_LABELDECAYTIMEDRUM          1097
#define IDC_LABELRELEASETIMEDRUM        1098
#define IDC_LABELUNKNOWNDRUM            1099
#define IDC_LABELUNKNOWNDRUM2           1100
#define IDC_EDITCOARSETUNEDRUM          1101
#define IDC_EDITFINETUNEDRUM            1102
#define IDC_EDITATTACKTIMEDRUM          1103
#define IDC_EDITDECAYTIMEDRUM           1104
#define IDC_EDITRELEASETIMEDRUM         1105
#define IDC_EDITUNKNOWN1DRUM            1106
#define IDC_EDITUNKNOWN2DRUM            1107
#define IDC_LABELDRUMINSTRUMENT         1109
#define IDC_EDITDRUMINSTRUMENT          1110
#define IDC_BUTTONUP                    1653
#define IDC_BUTTONDOWN                  1654
#define IDC_COMBOSOUND                  1668
#define IDC_EDITSAMPLINGRATE            1669
#define IDC_COMBOSOUNDBANK              1670
#define IDC_EDITVOL                     1671
#define IDC_EDITPAN                     1672
#define IDC_EDITPRIORITY                1673
#define IDC_EDITTREMTYPE                1674
#define IDC_EDITTREMRATE                1675
#define IDC_EDITTREMDEPTH               1676
#define IDC_EDITTREMDELAY               1677
#define IDC_EDITTVIBTYPE                1678
#define IDC_EDITVIBRATE                 1679
#define IDC_EDITVIBDEPTH                1680
#define IDC_EDITVIBDELAY                1681
#define IDC_COMBOSOUND2                 1682
#define IDC_EDITSAMPLEPAN               1683
#define IDC_EDITSAMPLEVOL               1684
#define IDC_EDITATTACKTIME              1685
#define IDC_EDITDECAYTIME               1686
#define IDC_EDITRELEASETIME             1687
#define IDC_EDITATTACKVOLUME            1688
#define IDC_EDITDECAYVOLUME             1689
#define IDC_EDITVELMIN                  1690
#define IDC_EDITVELMAX                  1691
#define IDC_EDITKEYMIN                  1692
#define IDC_EDITKEYMAX                  1693
#define IDC_EDITKEYBASE                 1694
#define IDC_EDITDETUNE                  1695
#define IDC_EDITLENGTH                  1696
#define IDC_EDITBASE                    1697
#define IDC_EDITLOOP                    1698
#define IDC_EDITEND                     1699
#define IDC_EDITCOUNT                   1700
#define IDC_CHECKLOOPENABLED            1701
#define IDC_COMBOSOUNDSUBSOUND          1702
#define IDC_CHECKRAW                    1703
#define IDC_STATICL1                    1704
#define IDC_STATICL2                    1705
#define IDC_STATICL3                    1706
#define IDC_BUTTONRIP                   1707
#define IDC_BUTTONRIP2                  1707
#define IDC_STATICSFXBANKINST           1708
#define IDC_BUTTONRIP3                  1708
#define IDC_COMBOPERCUSSION             1709
#define IDC_BUTTONADDSOUND              1710
#define IDC_BUTTONDELETESOUND           1711
#define IDC_STATICSOUNDBANK             1712
#define IDC_COMBOSFX                    1712
#define IDC_BUTTONDELETESOUND2          1713
#define IDC_BUTTONADDSOUND2             1714
#define IDC_BUTTONIMPORT16BITRAW        1715
#define IDC_BUTTONEXPORTRAW             1716
#define IDC_BUTTONIMPORTPREDICTORS      1717
#define IDC_BUTTONEXPORTRAW2            1718
#define IDC_BUTTONEXPORTPREDITORS       1718
#define IDC_BUTTONIMPORTSDKTOOLS        1719
#define IDC_EDITTBLINDEX                1720
#define IDC_BUTTONVADPCMIMPORT          1767
#define IDC_BUTTONVADPCMIMPORTSAMEPRED  1768
#define ID_FILE_OPENROM                 32771
#define ID_FILE_QUIT                    32772
#define ID_FILE_OPENROMEXPLICIT         32773
#define ID_FILE_OPENKNOWNROM            32774
#define ID_OPENKNOWNROM_64DEHAKKEN      32775
#define ID_OPENKNOWNROM_64OOZUMOU       32776
#define ID_OPENKNOWNROM_64OOZUMOU2      32777
#define ID_OPENKNOWNROM_64TRUMPCOLLECTION 32778
#define ID_FILE_EXTRACTALLKNOWNGAMES    32779
#define ID_FILE_OPENSTARFOXROM          32780
#define ID_FILE_OPENROMN64PTRWAVETABLE2 32781

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32782
#define _APS_NEXT_CONTROL_VALUE         1047
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
